CREATE TABLE [dbo].[INDEX]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[indexName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INDEX] ADD CONSTRAINT [PK_INDEX] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
